### ISSUE TITLE
Update (backup) counting system for 2016

### ISSUE THREAD

**Issue by Procrat** [12urenloop/12urenloop#132]
- [ ] Update teams in counting system
- [ ] Update teams in manual counting system

**Comment by NoctuaNivalis** [comment]
The first is simple creating a new script like [this one](https://github.com/ZeusWPI/12urenloop/blob/master/count-von-count/scripts/teams2015.hs).

**Comment by feliciaan** [comment]
The backup System is just updating the initial db script.

**Comment by becousae** [comment]
Reopen this for 2017.
