### ISSUE TITLE
make a 12urenloop Org?

### ISSUE THREAD

**Issue by Iepoev** [12urenloop/12urenloop#166]
This repo is basically a bunch of seperate apps aggregated in a root folder. Wouldn't it be better to have this in a github org in seperate repos?

**Comment by wschella** [comment]
Since communication will often be related, seperate repo's will disperse information.
See issues, PR comments, ...

**Comment by Iepoev** [comment]
you can refer to other repos in comments, for example https://github.com/ZeusWPI/blokmap/issues/9

**Comment by Procrat** [comment]
What would the benefits be?

**Comment by Iepoev** [comment]
Every separate project having its own history, its own issues and its own PRs on its own branch network. we've got 16 issues and some don't have a clear indication to what project the belong. Branches are currently required to have a prefix that tells which project it belongs to. These aren't life-threatening issues, but it seems a logical change.

**Comment by NoctuaNivalis** [comment]
But we all love merging branches :-(

**Comment by iliclaey** [comment]
Is this something we might still consider, or should we just close this? It doesn't seem to be a bad idea to me.

**Comment by werthen** [comment]
Bit of an outsider on this one, but I think it's a good idea.

**Comment by becousae** [comment]
I agree

**Comment by iliclaey** [comment]
Great! [Transferring](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) the repo to an organisation shouldn't be too hard, as well as [splitting](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) each directory into it's own repo.

**Comment by iasoon** [comment]
I'm in favour of moving the websites out of this repository, but I'd keep the entire CVC system in the same repository.

Personally and for no sound reason, I don't like the idea of moving this code out of the Zeus organisation, especially CVC.

**Comment by becousae** [comment]
I think this could work. My main concern is the websites.

CVC has a more complex structure, with shared config files if I'm not mistaken. So that can stay together for me, in a Zeus Repo.

**Comment by NoctuaNivalis** [comment]
Moving the websites sounds like a good idea, then I can listen to updates on just the interesting parts.
