### ISSUE TITLE
Convert site to nanoc

### ISSUE THREAD

**Issue by becousae** [12urenloop/12urenloop#171]
Use nanoc to make the site a bit more dynamic.

This would allow to split the one huge html file into multiple partials,
to extract information like teams and make it easier to change them, ...

**Comment by becousae** [comment]
The site has been converted in [this branch](https://github.com/ZeusWPI/12urenloop/tree/nanoc-site).

Stuff to be done:
[ ] Split up existing files into more partials where needed
[ ] Extract all information that can change into data files
[ ] Convert css to scss
[ ] Convert js to coffeescript

**Comment by NoctuaNivalis** [comment]
- [ ] Ensure new deploy script does not fuck up freezing
