### ISSUE TITLE
Recover gyrid img

### ISSUE THREAD

**Issue by Iepoev** [12urenloop/12urenloop#177]
@Procrat any idea how we can flash the gyrid image of last year to the memory cards?
it's 100MB so it must have been compressed somehow. @NoctuaNivalis assumes that null-padding was removed.

**Comment by Procrat** [comment]
We just used `dd` IIRC. 100MB shouldn't take that long, right?

Best of luck with the preparations!

**Comment by Procrat** [comment]
You could also mount the image and copy the files, I guess. I don't know if that would be faster.

**Comment by NoctuaNivalis** [comment]
I'm assuming this has been solved. Perhaps someone should post the solution here and close this before we forget it again.

**Comment by NoctuaNivalis** [comment]
Since this is closed, I'm assuming someone documented this?

**Comment by becousae** [comment]
Because we are now working with the espresso bins, we are documenting all things we are doing.
We (hopefully) won't be using the gyrids again, so we won't be needing documentation for them.
