### ISSUE TITLE
Automatic Twitterwall

### ISSUE THREAD

**Issue by Silox** [12urenloop/12urenloop#75]
There was an idea to let something (Boxxy?) post automatich twitter messages when someone overtakes someone, when someone reaches a certain amount of laps, when someone ran X-kilometers etc. 

Seems like a good idea and pwetty cool to implement.

**Comment by Silox** [comment]
This could be used to communicate to twitter https://www.npmjs.com/package/twitter

**Comment by FelixVanderJeugt** [comment]
If that which you linked is a javascript API to twitter, then yes, this should be done with boxxy. It however says it's a node.js client. That should still work, but might be a bit harder.

**Comment by Silox** [comment]
It is possible to POST messages, yes: https://dev.twitter.com/rest/reference/post/statuses/update

**Comment by Procrat** [comment]
We should review the code.

**Comment by Iepoev** [comment]
I've reviewed the output and most of the features work as expected.
Lap speed records however are broken because the data is way too inaccurate to keep track of lap speed

**Comment by Procrat** [comment]
@Iepoev: Cool! So can you remove that part? Then that's one less thing we have to worry about! ^_^
